-- Nightshift Espresso Co. — MySQL schema
-- Run this once against your MySQL server:
--   mysql -u root -p < sql/mysql_schema.sql

CREATE DATABASE IF NOT EXISTS nightshift
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE nightshift;

CREATE TABLE IF NOT EXISTS transactions (
  transaction_id   VARCHAR(36)     NOT NULL PRIMARY KEY,   -- UUID, generated by the app
  store_location   VARCHAR(80)     NOT NULL,               -- e.g. "Downtown Loop"
  city             VARCHAR(60)     NOT NULL,
  barista_name     VARCHAR(80)     NOT NULL,
  customer_name    VARCHAR(120)    NULL,                   -- NULL = walk-in / anonymous
  product_name     VARCHAR(120)    NOT NULL,
  category         VARCHAR(40)     NOT NULL,               -- Espresso, Cold Brew, Pastry, Beans, Merch
  quantity         INT             NOT NULL DEFAULT 1,
  unit_price       DECIMAL(8,2)    NOT NULL,
  total_amount     DECIMAL(10,2)   NOT NULL,
  payment_method   VARCHAR(30)     NOT NULL,               -- Card, Cash, Mobile Wallet, Gift Card
  order_channel    VARCHAR(30)     NOT NULL,               -- Counter, Drive-Thru, Mobile App, Kiosk
  status           VARCHAR(20)     NOT NULL DEFAULT 'Completed', -- Completed, Refunded, Voided, Pending
  transaction_time DATETIME        NOT NULL,
  created_at       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
                                    ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_transaction_time (transaction_time),
  INDEX idx_store (store_location),
  INDEX idx_status (status)
) ENGINE=InnoDB;

-- A small view Power BI can point at directly if you'd rather not expose
-- create/update bookkeeping columns to the report.
CREATE OR REPLACE VIEW v_transactions AS
SELECT
  transaction_id,
  store_location,
  city,
  barista_name,
  customer_name,
  product_name,
  category,
  quantity,
  unit_price,
  total_amount,
  payment_method,
  order_channel,
  status,
  transaction_time
FROM transactions;
