-- Nightshift Espresso Co. — Snowflake schema
-- Run this once in a Snowsight worksheet (or via SnowSQL).

CREATE DATABASE IF NOT EXISTS NIGHTSHIFT;
CREATE SCHEMA IF NOT EXISTS NIGHTSHIFT.PUBLIC;

USE DATABASE NIGHTSHIFT;
USE SCHEMA PUBLIC;

-- A small warehouse is plenty for this project. Auto-suspend keeps costs at ~0
-- when the local app isn't actively writing.
CREATE WAREHOUSE IF NOT EXISTS NIGHTSHIFT_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
  TRANSACTION_ID   VARCHAR(36)     NOT NULL,
  STORE_LOCATION   VARCHAR(80)     NOT NULL,
  CITY             VARCHAR(60)     NOT NULL,
  BARISTA_NAME     VARCHAR(80)     NOT NULL,
  CUSTOMER_NAME    VARCHAR(120),
  PRODUCT_NAME     VARCHAR(120)    NOT NULL,
  CATEGORY         VARCHAR(40)     NOT NULL,
  QUANTITY         NUMBER(10,0)    NOT NULL DEFAULT 1,
  UNIT_PRICE       NUMBER(8,2)     NOT NULL,
  TOTAL_AMOUNT     NUMBER(10,2)    NOT NULL,
  PAYMENT_METHOD   VARCHAR(30)     NOT NULL,
  ORDER_CHANNEL    VARCHAR(30)     NOT NULL,
  STATUS           VARCHAR(20)     NOT NULL DEFAULT 'Completed',
  TRANSACTION_TIME TIMESTAMP_NTZ   NOT NULL,
  CREATED_AT       TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT       TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (TRANSACTION_ID)
);

-- Convenience view, mirroring the MySQL one, for Power BI.
CREATE OR REPLACE VIEW V_TRANSACTIONS AS
SELECT
  TRANSACTION_ID,
  STORE_LOCATION,
  CITY,
  BARISTA_NAME,
  CUSTOMER_NAME,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  PAYMENT_METHOD,
  ORDER_CHANNEL,
  STATUS,
  TRANSACTION_TIME
FROM TRANSACTIONS;
